#! /bin/sh

# Background Process
sxhkd &
dunst &
wal -R 

bspc monitor eDP1 -d I II III IV V
bspc monitor VGA1 -d VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set the colors.
. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

#bspc rule -a Firefox desktop='^1'
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
